#!/usr/bin/env python

import os
import sys
import errno

def main(argv):
    if len(argv) < 2:
        print "usage:\n\t%s command [args..]" % argv[0]
        return 1
    
    pid, master_fd = os.forkpty()

    if pid > 0:
        master = os.fdopen(master_fd, "r", 0)

        try:
            data = master.readline()
            while data:
                sys.stdout.write(data)
                data = master.readline()
        except IOError, e:
            if e.errno != errno.EIO:
                print >> sys.stderr, "Error:", e

        ret, status = os.waitpid(pid, 0)
        return os.WEXITSTATUS(status)

    elif pid == 0:
        os.execvp(argv[1], argv[1:])
        sys.exit(2)

if __name__ == "__main__":
    sys.exit(main(sys.argv))
